
The following have been reloaded with a version change:
  1) GCCcore/7.3.0 => GCCcore/8.2.0
  2) binutils/2.30-GCCcore-7.3.0 => binutils/2.31.1-GCCcore-8.2.0
  3) bzip2/1.0.6-GCCcore-7.3.0 => bzip2/1.0.6-GCCcore-8.2.0
  4) iccifort/2020.4.304 => iccifort/2019.1.144-GCC-8.2.0-2.31.1
  5) iimpi/2020b => iimpi/2019a
  6) imkl/2020.4.304-iimpi-2020b => imkl/2019.1.144-iimpi-2019a
  7) impi/2019.9.304-iccifort-2020.4.304 => impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1
  8) intel/2020b => intel/2019a
  9) ncurses/6.1-GCCcore-7.3.0 => ncurses/6.1-GCCcore-8.2.0

Traceback (most recent call last):
  File "model.py", line 1137, in <module>
    train_dat, valid_dat = preProcessing(args.training_data_path, args.model_saving_path)
  File "model.py", line 965, in preProcessing
    X_v, X_c, Y_v, Y_c  = loadData(prefix, train_file)
  File "model.py", line 61, in loadData
    data = np.load(prefix + filename)
  File "/usr/cluster/contrib/Python/3.7.6-intel-2019a-2013/lib/python3.7/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/umbc/rs/nasa-access/xin/cloud-phase-prediction/data/training//umbc/rs/nasa-access/xin/cloud-phase-prediction/data/training/2017_jan_day_005.npz'
